---

- name: Install Chrony
  yum:
    name: 'chrony'
    state: latest
  tags:
    - chrony-install
    - sys-prepare

- name: Enable Chrony
  systemd:
    name: chronyd
    enabled: yes
    state: started
  tags:
    - chrony-install
    - sys-prepare

- name: Install Git
  yum:
    name: git
    state: latest

- name: Update system
  yum:
    name: '*'
    state: latest
