---

- name: Install Chrony
  dnf:
    name: 'chrony'
    state: latest
  tags:
    - chrony-install
    - sys-prepare

- name: Enable Chrony
  systemd:
    name: chrony
    enabled: yes
    state: started
  tags:
    - chrony-install
    - sys-prepare

- name: Install python3
  dnf:
  state: latest
  update_cache: yes

- name: Update system
  dnf:
    name: '*'
    state: latest

- name: System Reboot
  reboot:
    reboot_timeout: uptime