---

# Update Centos
- name: Update system
  dnf:
    name: "*"
    state: latest
  tags:
    - sys-prepare

- name: enable epel repository
  command: "yum -y install 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm'"
  become: yes
  tags:
    - sys-prepare

- name: enable powertools repository
  command: "yum config-manager --set-enabled powertools"
  tags:
    - sys-prepare

- name: Install packages
  dnf:
    name: ['chrony', 'nfs-utils', 'nfs4-acl-tools', 'net-tools', 'wget', 'firewalld', 'git']
    state: latest
  tags:
    - sys-prepare

# Enable services
- name: Enable Chrony
  systemd:
    name: 'chronyd'
    state: started
    enabled: yes
    masked: no
  tags:
    - sys-prepare

- name: Enable Firewalld
  systemd:
    name: 'firewalld'
    state: started
    enabled: yes
    masked: no
  tags:
    - sys-prepare