---

- name: Create namespace
  command: kubectl create namespace webapp-volumes
  become: no
  tags:
    - webapp

- name: Create App directory
  file:
    path: /home/ansible/webapp
    state: directory
  tags:
    - webapp

# Define storing

- name: Persisteng volume
  template:
    src: 'nfs-pv.yml.j2'
    dest: '/home/ansible/webapp/nfs-pv.yml'
    owner: root
    group: root
    mode: 0644
  tags:
    - webapp

- name: Apply 
  command: kubectl apply -f ~/webapp/nfs-pv.yml
  become: no
  tags:
    - webapp

- name: Assign pod volume
  template:
    src: 'nfs-pvc.yml.j2'
    dest: '/home/ansible/webapp/nfs-pvc.yml'
    owner: root
    group: root
    mode: 0644
  tags:
    - webapp

- name: Apply pods
  command: kubectl apply -f ~/webapp/nfs-pvc.yml
  become: no
  tags:
    - webapp

# Create deployment
- name: Create Deployment
  template:
    src: 'deployment.yml.j2'
    dest: '/home/ansible/webapp/webapp-volumes.yml'
    owner: root
    group: root
    mode: 0644
  tags:
    - webapp

- name: Apply deployment
  command: kubectl apply -f ~/webapp/webapp-volumes.yml
  become: no
  tags:
    - webapp