---

- name: Create namespace
  command: kubectl create namespace webapp-routed
  become: no
  tags:
    - webapp

- name: Create App directory
  file:
    path: /home/ansible/webapp
    state: directory
  tags:
    - webapp

# Create deployment
- name: Deployment file
  template:
    src: 'app.yml.j2'
    dest: '/home/ansible/webapp/app.yml'
    owner: root
    group: root
    mode: 0644
  tags:
    - webapp

- name: Apply deployment
  command: kubectl apply -f ~/webapp/app.yml
  become: no
  tags:
    - webapp

# Create Ingress controller
- name: Ingress file
  template:
    src: 'ingress.yml.j2'
    dest: '/home/ansible/webapp/ingress.yml'
    owner: root
    group: root
    mode: 0644
  tags:
    - webapp

- name: Apply ingress file
  command: kubectl apply -f ~/webapp/ingress.yml
  become: no
  tags:
    - webapp

# Create configMap
- name: ConfigMap file
  template:
    src: 'configmap.yml.j2'
    dest: '/home/ansible/webapp/configmap.yml'
    owner: root
    group: root
    mode: 0644
  tags:
    - webapp

- name: Apply configmap file
  command: kubectl apply -f ~/webapp/configmap.yml
  become: no
  tags:
    - webapp

# Define storing

- name: Persisteng volume
  template:
    src: 'nfs-pv.yml.j2'
    dest: '/home/ansible/webapp/nfs-pv.yml'
    owner: root
    group: root
    mode: 0644
  tags:
    - webapp

- name: Apply 
  command: kubectl apply -f ~/webapp/nfs-pv.yml
  become: no
  tags:
    - webapp

- name: Assign pod volume
  template:
    src: 'nfs-pvc.yml.j2'
    dest: '/home/ansible/webapp/nfs-pvc.yml'
    owner: root
    group: root
    mode: 0644
  tags:
    - webapp

- name: Apply pods
  command: kubectl apply -f ~/webapp/nfs-pvc.yml
  become: no
  tags:
    - webapp
