---

- name: Install haproxy (Red Hat)
  yum:
    name: haproxy
    state: present
  when: ansible_os_family == 'RedHat'

- name: Configure haproxy (Red Hat)
  template: 
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
    setype: etc_t
  become: yes
  when: ansible_os_family == 'RedHat'

- name: Certificate files
  copy:
    src: "{{ item }}"
    dest: "/etc/ssl/certs/{{ item }}"
    owner: root
    group: root
    mode: 0644
    setype: cert_t
  when: ansible_os_family == 'RedHat'
  with_items:
    - "acme.es.pem"
    - "cacert.pem"
