---
- hosts: master
  gather_facts: yes
  become: yes
  roles:
    #- { role: haproxy, tags: haproxy}
    - { role: master, tags: ['k8s-master', 'calico', 'user', 'k8s-ingress'] }    
    - { role: webapp, tags: ['webapp'] }